<?php

use Application\Controller\CoreController;

# Load User Index Permissions as base for navigation
$aIndexPermissions = CoreController::$oSession->oUser->getMyPermissions('index',true);
?>
<li class="sidebar-item active">
    <a href="#dashboards" data-toggle="collapse" class="font-weight-bold sidebar-link">
        <i class="align-middle" data-feather="home"></i> <span class="align-middle">Dashboard</span>
    </a>
    <ul id="dashboards" class="sidebar-dropdown list-unstyled collapse show">
        <?php foreach(array_keys($aIndexPermissions) as $sModule) {
            $aInfo = $aIndexPermissions[$sModule];
            # Home is empty because there is no home permission
            if(count($aInfo) == 0) {
                $aInfo = ['index'=>(object)['nav_label'=>'Home','nav_href'=>'/']];
            }
            if($aInfo['index']->show_in_menu != 1) {
                continue;
            }
            # check if we are on active node
            $sActive = ('/'.strtolower($this->sRouteName) == strtolower($aInfo['index']->nav_href)) ? ' active' : '';
            # home is special case ..
            $sActive = ($this->sRouteName == 'home' && $aInfo['index']->nav_href == '/') ? ' active' : $sActive;

            $sIconName = substr($aInfo['index']->nav_href,1);

            $bHasParam = stripos($sIconName,'?');
            if($bHasParam === false) {

            } else {
                $sIconName = substr($sIconName,0,$bHasParam);
            }
            $sIcon = (array_key_exists($sIconName.'-icon',CoreController::$aGlobalSettings))
                ?  CoreController::$aGlobalSettings[$sIconName.'-icon'] : '';
            ?>
            <li class="sidebar-item">
                <a class="sidebar-link" href="<?=$aInfo['index']->nav_href?>">
                    <?=($sIcon != '') ? '<i class="'.$sIcon.'"></i> ' : ''?>
                    <?=$this->translate($aInfo['index']->nav_label)?>
                </a>
            </li>
        <?php } ?>
    </ul>
</li>