<?php
use Application\Controller\CoreController;
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle(CoreController::$aGlobalSettings['app-title'])->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('/themes/vuze/assets/css/style.css'))
        ->prependStylesheet($this->basePath('/themes/vuze/assets/css/app.css'))
        ->prependStylesheet($this->basePath('/vendor/uppy/dist/uppy.min.css'))
        ->prependStylesheet($this->basePath('/vendor/summernote/dist/summernote-bs4.min.css'))
        ->prependStylesheet($this->basePath('/vendor/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.min.css'))
        ->prependStylesheet($this->basePath('/vendor/filepond/dist/filepond.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->inlineScript()
        ->prependFile($this->basePath('/js/plc-message.js'))
        ->prependFile($this->basePath('/js/listener.js'))
        ->prependFile($this->basePath('/vendor/sweetalert/dist/sweetalert.min.js'))
        ->prependFile($this->basePath('/vendor/summernote/dist/summernote-bs4.min.js'))
        ->prependFile($this->basePath('/vendor/jquery-ui-sortable/jquery-ui.min.js'))
        ->prependFile($this->basePath('/themes/vuze/assets/js/app.js'))
    ?>
    <!-- Load FilePond library -->
    <script src="/vendor/filepond-plugin-image-exif-orientation/dist/filepond-plugin-image-exif-orientation.min.js"></script>
    <script src="/vendor/filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.min.js"></script>
    <script src="/vendor/filepond-plugin-image-validate-size/dist/filepond-plugin-image-validate-size.min.js"></script>
    <script src="/vendor/filepond-plugin-image-resize/dist/filepond-plugin-image-resize.min.js"></script>
    <script src="/vendor/filepond-plugin-image-crop/dist/filepond-plugin-image-crop.min.js"></script>
    <script src="/vendor/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.min.js"></script>
    <script src="/vendor/filepond-plugin-image-transform/dist/filepond-plugin-image-transform.min.js"></script>
    <script src="/vendor/filepond/dist/filepond.min.js"></script>
    <!-- Turn all file input elements into ponds -->
</head>

<body>
<div class="wrapper">
    <nav class="sidebar sidebar-sticky">
        <div class="sidebar-content  js-simplebar">
            <a class="sidebar-brand" href="/">
                <img src="/img/logo.png" style="max-height:60px; max-width:120px;" />
            </a>

            <ul class="sidebar-nav">
                <?php
                /**
                 * Try to load theme based navigation - or get default navigation instead
                 */
                try {
                    echo $this->partial('partial/nav-'.CoreController::$oSession->oUser->getTheme());
                } catch(\RuntimeException $e) {
                    try {
                        // no nav partial for theme found - load default
                        echo $this->partial('partial/nav');
                    } catch(\RuntimeException $e) {
                        // no nav partial found
                    }
                }
                ?>
            </ul>

            <?php
            if(!isset(CoreController::$oSession->aLicences['info-instance-id'])) {
            ?>
            <div class="sidebar-cta">
                <!--
                <button type="button" class="close sidebar-cta-close" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button> -->
                <div class="sidebar-cta-content">
                    <strong class="d-inline-block mb-1">Get Premium Support</strong>
                    <div class="mb-2">
                        If you like onePlace, consider a subscription based model
                        for premium support and extended features
                    </div>
                    <a href="https://1plc.ch" class="btn btn-outline-primary" target="_blank">Upgrade</a>
                </div>
            </div>
            <?php } ?>
        </div>
    </nav>

    <div class="main">
        <nav class="navbar navbar-expand navbar-light bg-white sticky-top">
            <a class="sidebar-toggle d-flex mr-3">
                <i class="align-self-center" data-feather="menu"></i>
            </a>

            <form class="form-inline d-none d-sm-inline-block">
                <?php if(CoreController::$oSession->oUser->hasPermission('quicksearch','Application-Controller-IndexController')) { ?>
                    <?=$this->partial('partial/quicksearch',[])?>
                <?php } ?>
            </form>

            <div class="navbar-collapse collapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-icon dropdown-toggle ml-2 d-inline-block d-sm-none" href="#" data-toggle="dropdown">
                            <div class="position-relative">
                                <i class="align-middle mt-n1" data-feather="settings"></i>
                            </div>
                        </a>
                        <a class="nav-link nav-link-user dropdown-toggle d-none d-sm-inline-block" href="#" data-toggle="dropdown">
                            <img src="https://via.placeholder.com/156x156" class="avatar img-fluid rounded mr-1" alt="<?=CoreController::$oSession->oUser->getLabel()?>" />
                            <span class="text-dark"><?=CoreController::$oSession->oUser->getLabel()?>
                                <?php
                                $aUserXPInfo = CoreController::$oSession->oUser->getExperience();
                                ?>
                                - <small><?=$this->translate('Level')?> <?=$aUserXPInfo['level']?></small>
                            </span>
                        </a>
                        <div class="nav-text" style="width:100px; margin:-10px 0 0 56px;">
                            <div class="progress py-1" style="margin-top:2px;">
                                <div class="progress-bar" role="progressbar" style="width: <?=$aUserXPInfo['percent']?>%" aria-valuenow="<?=$aUserXPInfo['percent']?>" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        </div>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item" href="<?=$this->url('user',['action'=>'profile'])?>">
                                <?=$this->translate('Profile')?>
                            </a>
                            <a class="dropdown-item" href="<?=$this->url('user',['action'=>'settings'])?>">
                                <?=$this->translate('Settings')?>
                            </a>
                            <a class="dropdown-item" href="<?=$this->url('logout')?>">
                                <?=$this->translate('Sign out')?>
                            </a>
                        </div>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-icon dropdown-toggle ml-2" href="#" data-toggle="dropdown">
                            <div class="position-relative">
                                <i class="align-middle fas fa-envelope"></i>
                                <span class="indicator">0</span>
                            </div>
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-icon dropdown-toggle ml-2" href="#" id="alertsDropdown" data-toggle="dropdown">
                            <div class="position-relative">
                                <i class="align-middle fas fa-bell"></i>
                            </div>
                        </a>
                    </li>

                </ul>
            </div>
        </nav>

        <main class="content">
            <div class="container-fluid p-0">
                <?php
                /**
                 * Print Flashmessenger messages (alerts)
                 */
                $flash = $this->flashMessenger();
                $flash->setMessageOpenFormat('<div%s style="">
                                 <ul><li>')
                    ->setMessageSeparatorString('</li><li>')
                    ->setMessageCloseString('</li></ul></div>');
                echo $flash->render('error',   ['alert', 'alert-dismissible', 'alert-danger', 'alert-plc']);
                echo $flash->render('info',    ['alert', 'alert-dismissible', 'alert-info', 'alert-plc']);
                echo $flash->render('default', ['alert', 'alert-dismissible', 'alert-info', 'alert-plc']);
                echo $flash->render('warning', ['alert', 'alert-dismissible', 'alert-warning', 'alert-plc']);
                echo $flash->render('success', ['alert', 'alert-dismissible', 'alert-success', 'alert-plc']);?>

                <?= $this->partial('partial/breadcrumb', ['aButtons'=>isset($this->aButtons) ? $this->aButtons : [], 'aLinks'=>$this->aNavLinks]); ?>

                <?= $this->content ?>
            </div>
        </main>

        <footer class="footer">
            <div class="container-fluid">
                <div class="row text-muted">
                    <div class="col-6 text-left">
                        <p class="mb-0">
                            &copy; 2020 onePlace - Theme Vuze by <a href="https://bootlab.io" class="text-muted" target="_blank">bootlab.io</a>
                            - <?=(isset($this->recentPerfU)) ? 'Seite generiert in '.$this->recentPerfU.' ms' : ''?>
                        </p>
                    </div>
                    <div class="col-6 text-right">
                        <ul class="list-inline">
                            <li class="list-inline-item">
                                <a class="text-muted" href="#">
                                    <?=$this->translate('About us')?>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a class="text-muted" href="#">
                                    <?=$this->translate('Help')?>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a class="text-muted" href="#">
                                    <?=$this->translate('Contact')?>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a class="text-muted" href="#">
                                    <?=$this->translate('Terms & Conditions')?>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
    </div>
</div>

</body>

</html>