<?php
use Application\Controller\CoreController;
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('onePlace X - RC 1')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('themes/vuze/assets/css/style.css'))
        ->prependStylesheet($this->basePath('themes/vuze/assets/css/app.css'))
        ->prependStylesheet($this->basePath('vendor/select2/css/select2.min.css'))
        ->prependStylesheet($this->basePath('vendor/fontawesome/css/all.min.css'))
    ?>

    <!-- Filepond stylesheet -->
    <link href="https://unpkg.com/filepond/dist/filepond.css" rel="stylesheet">
    <link href="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css" rel="stylesheet">

    <!-- Scripts -->
    <?= $this->inlineScript()
        ->prependFile($this->basePath('vendor/select2/js/select2.full.min.js'))
        ->prependFile($this->basePath('themes/vuze/assets/js/app.js'))
    ?>
    <link href="https://transloadit.edgly.net/releases/uppy/v1.8.0/uppy.min.css" rel="stylesheet">
</head>

<body>
<div class="wrapper">
    <nav class="sidebar sidebar-sticky">
        <div class="sidebar-content  js-simplebar">
            <a class="sidebar-brand" href="/">
                <i class="align-middle" data-feather="layers"></i>
                <span class="align-middle">onePlace X</span>
            </a>

            <ul class="sidebar-nav">
                <?php
                /**
                 * Try to load theme based navigation - or get default navigation instead
                 */
                try {
                    echo $this->partial('partial/nav-'.CoreController::$oSession->oUser->getTheme());
                } catch(\RuntimeException $e) {
                    try {
                        // no nav partial for theme found - load default
                        echo $this->partial('partial/nav');
                    } catch(\RuntimeException $e) {
                        // no nav partial found
                    }
                }
                ?>
            </ul>

            <div class="sidebar-cta">
                <!--
                <button type="button" class="close sidebar-cta-close" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button> -->
                <div class="sidebar-cta-content">
                    <strong class="d-inline-block mb-1">Get Premium Support</strong>
                    <div class="mb-2">
                        If you like onePlace, consider a subscription based model
                        for premium support and extended features
                    </div>
                    <a href="https://1plc.ch" class="btn btn-outline-primary" target="_blank">Upgrade</a>
                </div>
            </div>
        </div>
    </nav>

    <div class="main">
        <nav class="navbar navbar-expand navbar-light bg-white sticky-top">
            <a class="sidebar-toggle d-flex mr-3">
                <i class="align-self-center" data-feather="menu"></i>
            </a>

            <form class="form-inline d-none d-sm-inline-block">
                <input class="form-control form-control-no-border navbar-search mr-sm-2" type="text" placeholder="Search topics..." aria-label="Search">
            </form>

            <div class="navbar-collapse collapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-icon dropdown-toggle ml-2 d-inline-block d-sm-none" href="#" data-toggle="dropdown">
                            <div class="position-relative">
                                <i class="align-middle mt-n1" data-feather="settings"></i>
                            </div>
                        </a>
                        <a class="nav-link nav-link-user dropdown-toggle d-none d-sm-inline-block" href="#" data-toggle="dropdown">
                            <img src="https://via.placeholder.com/156x156" class="avatar img-fluid rounded mr-1" alt="<?=CoreController::$oSession->oUser->getLabel()?>" />
                            <span class="text-dark"><?=CoreController::$oSession->oUser->getLabel()?>
                                <?php
                                $aUserXPInfo = CoreController::$oSession->oUser->getExperience();
                                ?>
                                - <small><?=$this->translate('Level')?> <?=$aUserXPInfo['level']?></small>
                            </span>
                        </a>
                        <div class="nav-text" style="width:100px; margin:-10px 0 0 56px;">
                            <div class="progress py-1" style="margin-top:2px;">
                                <div class="progress-bar" role="progressbar" style="width: <?=$aUserXPInfo['percent']?>%" aria-valuenow="<?=$aUserXPInfo['percent']?>" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        </div>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item" href="<?=$this->url('logout')?>">
                                <?=$this->translate('Sign out')?>
                            </a>
                        </div>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-icon dropdown-toggle ml-2" href="#" data-toggle="dropdown">
                            <div class="position-relative">
                                <i class="align-middle fas fa-envelope"></i>
                                <span class="indicator">0</span>
                            </div>
                        </a>
                        <!--
                        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right py-0">
                            <div class="dropdown-menu-header">
                                <div class="position-relative">
                                    4 New Messages
                                </div>
                            </div>
                            <div class="list-group">
                                <a href="#" class="list-group-item">
                                    <div class="row no-gutters align-items-center">
                                        <div class="col-2">
                                            <img src="https://via.placeholder.com/156x156" class="avatar img-fluid rounded-circle" alt="Kathy Davis">
                                        </div>
                                        <div class="col-10 pl-2">
                                            <div class="text-dark">Kathy Davis</div>
                                            <div class="text-muted small mt-1">Nam pretium turpis et arcu. Duis arcu tortor.</div>
                                            <div class="text-muted small mt-1">15m ago</div>
                                        </div>
                                    </div>
                                </a>
                                <a href="#" class="list-group-item">
                                    <div class="row no-gutters align-items-center">
                                        <div class="col-2">
                                            <img src="https://via.placeholder.com/156x156" class="avatar img-fluid rounded-circle" alt="John Smith">
                                        </div>
                                        <div class="col-10 pl-2">
                                            <div class="text-dark">John Smith</div>
                                            <div class="text-muted small mt-1">Curabitur ligula sapien euismod vitae.</div>
                                            <div class="text-muted small mt-1">2h ago</div>
                                        </div>
                                    </div>
                                </a>
                                <a href="#" class="list-group-item">
                                    <div class="row no-gutters align-items-center">
                                        <div class="col-2">
                                            <img src="https://via.placeholder.com/156x156" class="avatar img-fluid rounded-circle" alt="Marie Salter">
                                        </div>
                                        <div class="col-10 pl-2">
                                            <div class="text-dark">Marie Salter</div>
                                            <div class="text-muted small mt-1">Pellentesque auctor neque nec urna.</div>
                                            <div class="text-muted small mt-1">4h ago</div>
                                        </div>
                                    </div>
                                </a>
                                <a href="#" class="list-group-item">
                                    <div class="row no-gutters align-items-center">
                                        <div class="col-2">
                                            <img src="https://via.placeholder.com/156x156" class="avatar img-fluid rounded-circle" alt="Teresa Lessard">
                                        </div>
                                        <div class="col-10 pl-2">
                                            <div class="text-dark">Teresa Lessard</div>
                                            <div class="text-muted small mt-1">Aenean tellus metus, bibendum sed, posuere ac, mattis non.</div>
                                            <div class="text-muted small mt-1">5h ago</div>
                                        </div>
                                    </div>
                                </a>
                            </div>
                            <div class="dropdown-menu-footer">
                                <a href="#" class="text-muted">Show all messages</a>
                            </div>
                        </div> -->
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-icon dropdown-toggle ml-2" href="#" id="alertsDropdown" data-toggle="dropdown">
                            <div class="position-relative">
                                <i class="align-middle fas fa-bell"></i>
                            </div>
                        </a>
                        <!--
                        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right py-0" aria-labelledby="alertsDropdown">
                            <div class="dropdown-menu-header">
                                4 New Notifications
                            </div>
                            <div class="list-group">
                                <a href="#" class="list-group-item">
                                    <div class="row no-gutters align-items-center">
                                        <div class="col-2">
                                            <i class="text-danger" data-feather="alert-circle"></i>
                                        </div>
                                        <div class="col-10">
                                            <div class="text-dark">Update completed</div>
                                            <div class="text-muted small mt-1">Restart server 12 to complete the update.</div>
                                            <div class="text-muted small mt-1">2h ago</div>
                                        </div>
                                    </div>
                                </a>
                                <a href="#" class="list-group-item">
                                    <div class="row no-gutters align-items-center">
                                        <div class="col-2">
                                            <i class="text-warning" data-feather="bell"></i>
                                        </div>
                                        <div class="col-10">
                                            <div class="text-dark">Lorem ipsum</div>
                                            <div class="text-muted small mt-1">Aliquam ex eros, imperdiet vulputate hendrerit et.</div>
                                            <div class="text-muted small mt-1">6h ago</div>
                                        </div>
                                    </div>
                                </a>
                                <a href="#" class="list-group-item">
                                    <div class="row no-gutters align-items-center">
                                        <div class="col-2">
                                            <i class="text-primary" data-feather="home"></i>
                                        </div>
                                        <div class="col-10">
                                            <div class="text-dark">Login from 192.186.1.1</div>
                                            <div class="text-muted small mt-1">8h ago</div>
                                        </div>
                                    </div>
                                </a>
                                <a href="#" class="list-group-item">
                                    <div class="row no-gutters align-items-center">
                                        <div class="col-2">
                                            <i class="text-success" data-feather="user-plus"></i>
                                        </div>
                                        <div class="col-10">
                                            <div class="text-dark">New connection</div>
                                            <div class="text-muted small mt-1">Anna accepted your request.</div>
                                            <div class="text-muted small mt-1">12h ago</div>
                                        </div>
                                    </div>
                                </a>
                            </div>
                            <div class="dropdown-menu-footer">
                                <a href="#" class="text-muted">Show all notifications</a>
                            </div>
                        </div>
                        --->
                    </li>

                </ul>
            </div>
        </nav>

        <main class="content">
            <div class="container-fluid p-0">
                <?php
                /**
                 * Print Flashmessenger messages (alerts)
                 */
                $flash = $this->flashMessenger();
                $flash->setMessageOpenFormat('<div%s style="">
                                 <ul><li>')
                    ->setMessageSeparatorString('</li><li>')
                    ->setMessageCloseString('</li></ul></div>');
                echo $flash->render('error',   ['alert', 'alert-dismissible', 'alert-danger', 'alert-plc']);
                echo $flash->render('info',    ['alert', 'alert-dismissible', 'alert-info', 'alert-plc']);
                echo $flash->render('default', ['alert', 'alert-dismissible', 'alert-info', 'alert-plc']);
                echo $flash->render('warning', ['alert', 'alert-dismissible', 'alert-warning', 'alert-plc']);
                echo $flash->render('success', ['alert', 'alert-dismissible', 'alert-success', 'alert-plc']);?>

                <?= $this->partial('partial/breadcrumb', ['aButtons'=>isset($this->aButtons) ? $this->aButtons : [], 'pages'=>[]]); ?>

                <?= $this->content ?>
            </div>
        </main>

        <footer class="footer">
            <div class="container-fluid">
                <div class="row text-muted">
                    <div class="col-6 text-left">
                        <p class="mb-0">
                            &copy; <a href="index.html" class="text-muted">Vuze</a>
                            - <?=(isset($this->recentPerfU)) ? 'Seite generiert in '.$this->recentPerfU.' ms' : ''?>
                        </p>
                    </div>
                    <div class="col-6 text-right">
                        <ul class="list-inline">
                            <li class="list-inline-item">
                                <a class="text-muted" href="#">About us</a>
                            </li>
                            <li class="list-inline-item">
                                <a class="text-muted" href="#">Help</a>
                            </li>
                            <li class="list-inline-item">
                                <a class="text-muted" href="#">Contact</a>
                            </li>
                            <li class="list-inline-item">
                                <a class="text-muted" href="#">Terms & Conditions</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
    </div>
</div>

<!-- VUZE Theme js -->
<script src="js/app.js"></script>

<!-- jquery ui -->
<script src="vendor/jquery-ui/jquery-ui.min.js" />

<!-- sweet alert for all alerts -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

<!-- oneplace core scripts -->
<script src="/js/listener.js"></script>
<script src="/js/plc-message.js"></script>
</body>

</html>